num_1 = int(input())
num_2 = int(input())
num_3 = int(input())
num_4 = int(input())
num_5 = int(input())
print('Наименьшее число =', min(num_1, num_2, num_3, num_4, num_5))
print('Наибольшее число =', max(num_1, num_2, num_3, num_4, num_5))